CREATE TABLE IF NOT EXISTS `#__books` (
	`id` int(11) unsigned NOT NULL AUTO_INCREMENT,
	`asset_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'FK to the #__assets table.',
	`catid` int(11) unsigned NOT NULL DEFAULT '0',
	`type` VARCHAR(12) NOT NULL,
	`name` VARCHAR(111) NOT NULL,
	`author` VARCHAR(50) NOT NULL,
	`description` VARCHAR(900) NOT NULL,
	`short_description` VARCHAR(111) NOT NULL,
	`ribbon_text` VARCHAR(12) NOT NULL,
	`ribbon_color` VARCHAR(16) NOT NULL,
	`cover_top_color` VARCHAR(16) NOT NULL,
	`cover_buttom_color` VARCHAR(16) NOT NULL,
	`cover_image` VARCHAR(111) NOT NULL,
	`book_direction` VARCHAR(12) NOT NULL,
	`link1` VARCHAR(111) NOT NULL,
	`link1_src` VARCHAR(211) NOT NULL,
	`link2` VARCHAR(12) NOT NULL,
	`link2_src` VARCHAR(211) NOT NULL,
	`alias` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '',
	`ordering` int(11) NOT NULL DEFAULT '0',
	`published` tinyint(3) NOT NULL DEFAULT '0',
	`checked_out` int(11) unsigned NOT NULL DEFAULT '0',
	`checked_out_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
	`created` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
	`created_by` int(11) unsigned NOT NULL DEFAULT '0',
	`created_by_alias` varchar(255) NOT NULL DEFAULT '',
	`modified` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
	`modified_by` int(11) unsigned NOT NULL DEFAULT '0',
	`publish_up` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
	`publish_down` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
	`images` text NOT NULL,
	`version` int(11) unsigned NOT NULL DEFAULT '1',
	`hits` int(11) NOT NULL DEFAULT '0',
	`access` int(11) unsigned NOT NULL DEFAULT '0',
	`language` char(7) NOT NULL COMMENT 'The language code for the article.',
	`params` text NOT NULL,
	`metadata` text NOT NULL,
	`metakey` text NOT NULL,
	`metadesc` text NOT NULL,
	PRIMARY KEY (id)
)
CHARACTER SET utf8
COLLATE utf8_general_ci;
